requirements: ../requirements.txt
solutions_pdf: true
run_tests: false
export_cell:
    instructions: ""
    pdf: false
    filtering: true
    pagebreaks: true
    run_tests: false
generate:
    course_id: 787690
    token: PSMfidPlA-v_syDz_TAIBg
    filtering: true
    pagebreaks: true
    zips: false
seed:
    variable: autograding
    autograder_value: True
    student_value: False
